COLORS = {
    "Czarny": "черный",
    "Zieleń khaki": "хаки",
    "Liliowy": "лиловый",
    "Zielony": "зеленый",
    "Khaki": "хаки",
    "różnokolorowy": "разноцветный",
    "Złocisty": "золотой",
    "Rdzawoczerwony": "медь",
    "Fuksja": "фуксия",
    "Oliwkowozielony": "оливковый",
    "Kremowy/Czarny": "светло-бежевый;черный",
    "brązowy": "коричневый",
    "Limonkowy": "зеленый",
    "Biały": "белый",
    "Jasnoszary": "светло-серый",
    "Szary": "серый",
    "Kremowy": "светло-бежевый",
    "Czerwony": "красный",
    "Jasnobeżowy": "светло-бежевый",
    "Beżowy": "бежевый",
    "Turkusowy": "бирюзовый",
    "Niebieski": "синий",
    "Jasnoniebieski": "голубой",
    "Ciemnozielony": "темно-зеленый",
    "Ciemnofioletowy": "фиолетовый",
    "Fioletowy": "фиолетовый",
    "Jaskrawoniebieski": "синий",
    "Żółty": "желтый",
    "Różowy": "розовый",
    "Koralowy": "красный",
    "Ciemnobrązowy":"темно-коричневый",
    "Ciemnobrązowy/Brokatowy":"темно-коричневый",
    "Jasnobeżowy/Panterka":"разноцветный",
    "Niebieskoszary":"серый;голубой",
    "Jasnożółty":"желтый",
    "Wiśniowy":"красный",
    "Ciemnopomarańczowy":"оранжевый",
    "Czarny/Wzór":"черный",
    "Jasnoróżowy":"светло-розовый",
    "Miętowozielony":"зеленый",
    "Jasnozielony":"светло-зеленый",
    "Ciemna zieleń khaki":"хаки"
}
