MATERIALS = {
    "metallisedfibre":"металлизированное волокно",
    "Guma termoplastyczna":"термопластичная резина",
    "Poliuretan termoplastyczny":"Термопластик (TPU)",
    "cowleather":"Натуральная кожа",
    "goatleather":"Натуральная кожа",
    "Poliester":"Полиэстер",
    "Bawełna":"Хлопок",
    "sheepleather":"Натуральная кожа",
    "sbs":"Искусственный каучук",
    "linen":"Лен",
    "elastodiene":"Эластодиен",
    "Poliamid":"Полиамид",
    "Elastan":"Эластан",
    "paper":"бумага",
    "Skóra":"Натуральная кожа",
    "Polipropylen":"Полипропилен",
    "ethylenevinylacetate":"Этилвинилацетат",
    "vulcanizedrubber":"Вулканизированная резина",
    "nylon":"Нейлон",
    "Guma":"Резина",
    "jute":"Джут",
    "Akrylonitryl-Butadien-Styren":"Акрилонитрил-бутадиен-стирол",
    "straw":"Солома",
    "Wiskoza":"Вискоза",
    "Skóra regenerowana":"Восстановленная кожа",
    "rubber":"Каучук",
    "Poliuretan":"Полиуретан",
    "Mosiądz":"латунь",
    "wool":"Шерсть",
    "lyocell":"Лиоцелл",
    "modal":"Модал",
    "raffia":"Рафия",
    "acrylic":"Акрил",
    "cashmere":"Кашемир",
    "silk(mulberry)":"Шелк",
    "Stal":"Сталь",
    "lambskin":"Натуральная кожа",
    "palmtreeleaves":"Пальмовое волокно",
    "acetate":"Ацетат",
    "allyldiglycolcarbonate":"Пластик",
    "stainlesssteel":"Сталь",
    "Szkło akrylowe":"Стеклопластик",
    "Poliwęglan":"Поликарбонат",
    "PCTG":"Пластик",
    "Trójoctan":"Полимерный материал",
    "Metal":"Металл",
    "PETG":"Полимерный материал",
    "Zamsz":"Замша",
    "Modal":"Вискоза",
    "Szkło":"Стекло",
    "Aluminium":"Алюминий",
    "Etylen/octan":"",
    "Lyocell":"Лиоцелл"
}
